[build]
  base = "web"
  publish = "build"
  command = "pnpm run build"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
