[build]
  publish = "web/build/"
  command = "npm run --prefix web build"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"