[build]
  base = "web"
  publish = "build"
  command = "npm run build"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "*"
  to = "https://2anki.net"
  status = 200
  force = true # COMMENT: ensure that we always redirect