name: Deploy to 2anki.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: 'production'
    steps:
      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Dokku deploy
        uses: alemayhu/dokku-github-action@v7.2
        env:
          FORCE_DEPLOY: true
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: 2anki.net
          PROJECT: notion
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
