name: Integration Tests

on: [push]

jobs:
  build:
    if: github.actor!= 'dependabot'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          cd server
          npm install
          npm run build
          pip3 install setuptools==33.1.1
          pip3 install -r genanki/requirements.txt
          npm install -g ava
          npm run test
        env:
          CI: true
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
