name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          npm install -g pnpm
          pnpm --dir server install
          pnpm --dir server run build
          pip3 install -U setuptools 
          pip3 install -r server/genanki/requirements.txt
          pnpm --dir server run test
        env:
          CI: true
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
