name: Integration Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          pnpm install
          pnpm run test
        env:
          CI: true
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          SKIP_CREATE_DECK: true
